<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CalendarService.Application\CalendarService.Application.csproj" />
    <ProjectReference Include="..\CalendarService.Domain\CalendarService.Domain.csproj" />
  </ItemGroup>

</Project>
